# Generated by Django 4.2.2 on 2023-08-01 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Utilisateur')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('Telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=14, null=True, region=None, unique=True)),
                ('fonction', models.CharField(blank=True, max_length=60, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('Experience', models.IntegerField(blank=True, null=True)),
                ('competence1', models.CharField(blank=True, max_length=35, null=True, verbose_name='Compétence 1')),
                ('competence2', models.CharField(blank=True, max_length=35, null=True, verbose_name='Compétence 2')),
                ('competence3', models.CharField(blank=True, max_length=35, null=True, verbose_name='Compétence 3')),
                ('competence4', models.CharField(blank=True, max_length=35, null=True, verbose_name='Compétence 4')),
                ('competence5', models.CharField(blank=True, max_length=35, null=True, verbose_name='Compétence 5')),
                ('competence6', models.CharField(blank=True, max_length=35, null=True, verbose_name='Compétence 6')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='media/media/2.jpg', error_messages='Seule les images sont autorisées', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[270, 250], upload_to='media/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur par email',
                'verbose_name_plural': 'Utilisateurs par email',
            },
        ),
        migrations.CreateModel(
            name='Sujets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Python', max_length=200, verbose_name='Thème')),
                ('name', models.CharField(default='test', max_length=60, verbose_name='Titre')),
                ('description', models.TextField(default='test', max_length=1000, verbose_name='Description')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], error_messages='Seule les images sont autorisées', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 350], upload_to='img-titre')),
                ('created', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('participate', models.ManyToManyField(blank=True, null=True, related_name='participate', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Titre',
                'verbose_name_plural': 'Titres',
                'ordering': ['-created', '-update'],
            },
        ),
        migrations.CreateModel(
            name='MessagesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='Message')),
                ('creat', models.DateTimeField(auto_now=True)),
                ('mod', models.DateTimeField(auto_now_add=True)),
                ('sujets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.sujets', verbose_name='Sujets')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-creat', '-mod'],
            },
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='Message')),
                ('creat', models.DateTimeField(auto_now=True)),
                ('mod', models.DateTimeField(auto_now_add=True)),
                ('sujets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.sujets', verbose_name='Sujets')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-creat', '-mod'],
            },
        ),
    ]
