# Generated by Django 4.2.2 on 2023-08-02 14:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='media/media/2.jpg', error_messages='Seule les images sont autorisées', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[270, 250], upload_to='media/'),
        ),
    ]
