# Generated by Django 4.2.2 on 2023-08-02 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujets',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sujets',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Titre'),
        ),
        migrations.RemoveField(
            model_name='sujets',
            name='participate',
        ),
        migrations.AlterField(
            model_name='sujets',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujets',
            name='participate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participate', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
