# Generated by Django 4.2.2 on 2023-08-02 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_alter_sujets_description_alter_sujets_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujets',
            name='participate',
        ),
        migrations.AddField(
            model_name='sujets',
            name='participate',
            field=models.ManyToManyField(related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
