# Generated by Django 4.2.2 on 2023-08-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_remove_sujets_participate_sujets_participate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujets',
            name='likes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Utilisateur'),
        ),
    ]
